### ISSUE TITLE
astroquery.gaia not working in python 2.7

### ISSUE THREAD

**Issue by azariven** [astropy/astroquery#1404]
For some reason I'm constraint to using python 2.7 on a server I have no root access.

Here's the error message when I try to use the gaia module, does any one know what to do?
```
Traceback (most recent call last):
  File "star_query.py", line 55, in <module>
    from astroquery.gaia import Gaia
  File "/Users/azariven/anaconda2/lib/python2.7/site-packages/astroquery/gaia/__init__.py", line 39, in <module>
    from .core import Gaia, GaiaClass
  File "/Users/azariven/anaconda2/lib/python2.7/site-packages/astroquery/gaia/core.py", line 553, in <module>
    Gaia = GaiaClass()
  File "/Users/azariven/anaconda2/lib/python2.7/site-packages/astroquery/gaia/core.py", line 39, in __init__
    self.__gaiatap = TapPlus(url="http://gea.esac.esa.int/tap-server/tap")
  File "/Users/azariven/anaconda2/lib/python2.7/site-packages/astroquery/utils/tap/core.py", line 632, in __init__
    connhandler, verbose)
  File "/Users/azariven/anaconda2/lib/python2.7/site-packages/astroquery/utils/tap/core.py", line 97, in __init__
    print("Created TAP+ (v"+VERSION+") - Connection:\n" + str(self.__connHandler))
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by bsipocz** [comment]
@azariven - what version of astroquery are you using? Latest one can be installed with 
`pip install --pre --upgrade astroquery`

**Comment by azariven** [comment]
> @azariven - what version of astroquery are you using? Latest one can be installed with
> `pip install --pre --upgrade astroquery`

I'm using the latest version of astroquery-0.3.10.dev0

**Comment by keflavich** [comment]
Can you add a minimum working example here?  I am not sure what query you ran to produce this error.

Also, I cannot reproduce the failure-on-import locally on my python 2.7 build.

Finally, we are dropping support for python 2 moving forward.

**Comment by azariven** [comment]
Hi Adam,

Thanks for the response! It's been a while so I can't reproduce the error as well. We found a work around back then and the problem is mitigated.


Zhuchang
________________________________
