### ISSUE TITLE
Import fails on Python 2.7: from astroquery.mast import Catalogs (works on Python 3)

### ISSUE THREAD

**Issue by hippke** [astropy/astroquery#1358]
I can import ``from astroquery.mast import Catalogs``on Python 3, but not on Python 2:
```
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from astroquery.mast import Catalogs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Catalogs
```

```
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from astroquery.mast import Catalogs
>>> 
```

**Comment by bsipocz** [comment]
@hippke - What is the version of your astroquery? For me the import works on python2.7:
```
Python 2.7.15 (default, Sep 18 2018, 20:16:18) 
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from astroquery.mast import Catalogs

In [2]: 
```

**Comment by bsipocz** [comment]
(On the other hand, if I were you, I wouldn't spend much time now to make `tls` python2 compatible rather spend that time to switch to use the nice python3 only features either to make the code nicer, and faster...)

**Comment by hippke** [comment]
- I installed it today using ``pip install astroquery`` inside conda. With ``pip list`` I get ``astroquery 0.3.7``. This version has the bug.
- As a test, I installed from source (1 minute ago) and get ``0.3.10.dev5232``. With that version, it works.

When is the next pip release planned?

**Comment by hippke** [comment]
> (On the other hand, if I were you, I wouldn't spend much time now to make `tls` python2 compatible rather spend that time to switch to use the nice python3 only features either to make the code nicer, and faster...)

I see your point and I would have agreed totally, 4 weeks ago. However, I got a lot of feedback that people want to use TLS with Python 2. Explaining deprecation, conda etc. is an uphill battle for folks with a lot of legacy code. I already have a version that works with Python 2 single-threaded, and the last (known) bug is astroquery. So I like to try to make it work, at least. I won't make it fast on Python 2. It really lacks nice multithreading features.

**Comment by bsipocz** [comment]
@hippke - you need to use `pip install --upgrade` to get it upgraded. The latest manually released version is `0.3.8`, but we are continuously (automatically) releasing astroquery. Those releases are available to pip install by `pip install --pre --upgrade astroquery`.

**Comment by bsipocz** [comment]
> However, I got a lot of feedback that people want to use TLS with Python 2.

People will need to move on, all major packages either already dropped or are dropping python2 this year. astroquery is one of the last standing one as @keflavich is very understanding with people depending on CASA. The minute they are python3 compatible we're dropping python2 support here, too.
